Adding preprocessor variables for custom Wire pins
adafruit/RTClib pull request #226
Opened 2021-04-08 19:21 UTC by slyons

A minimal change to allow specifying custom SDA/SCL pins to pass through to the Wire library.

I'm using the names `RTCLIB_CUSTOM_SDA` and `RTCLIB_CUSTOM_SCL` to really drive home the point that it's outside the normal path.

2021-04-08 19:32 UTC, edgar-bonet commented
How is the user supposed to defined these macros? By modifying the source code of the library?

2021-04-08 19:40 UTC, slyons commented
If the `#define`

> How is the user supposed to defined these macros? By modifying the source code of the library?

I've been using it as such:

```C
#define RTCLIB_CUSTOM_SDA 13
#define RTCLIB_CUSTOM_SCL 14
#include "RTClib.h"
```
I originally added another `.begin` method but then didn't want to add too much duplicate code.

2021-04-08 20:55 UTC, ladyada commented
we will not take this, it doesnt work anyways.
please submit a PR where a &Wire object is passed in.

2021-04-08 20:56 UTC, ladyada requested changes
we dont allow this kind of adjustment to Wire, you can pass in a &Wire object instead

2021-05-18 16:12 UTC, klkl140 commented
Ive had the same problem about remapped I2C pins.
How about allowing begin() to have the arguments passed through to Wire.. like this:

in RTClib.h:
class RTC_DS1307 {
public:
  boolean begin(int sda=-1, int scl=-1);
...

in RTClib.cpp
boolean RTC_DS1307::begin(int sda, int scl) {
  Wire.begin(sda, scl);
...

Same for the other chips.
If this is acceptable I will try to make a pull request (will be my first...)

2021-05-18 16:13 UTC, ladyada commented
we would not accept it, you can use Wire.setPins() outside of RTClib

2021-05-18 17:13 UTC, klkl140 commented
But this would work on all I2C connections (?)
In my case I have two I2C, one default and the separate for the RTC.
To pass a &Wire object to RTClib is more complicated on the calling side, Wire already has the possibility to take pins.
How about this one without default values:

RTClib.h:
boolean begin();
boolean begin(int sda, int scl);

RTClib.cpp:
boolean RTC_DS1307::begin() {
    begin(SDA, SCL);  // these are used in Wire as defaults
}
boolean RTC_DS1307::begin(int sda, int scl) {
  Wire.begin(sda, scl);
...

2021-05-18 17:25 UTC, ladyada commented
that is not true - **only esp32 does this**. it would break every other board so it would not be merged

2021-05-18 17:58 UTC, klkl140 commented
ok.... I did not thought this is possible....
so your first advice would be best. Like its done in Adafruit_BMP3XX (?)
I'll give it a try

2021-05-20 11:03 UTC, klkl140 commented
it is working. But it will change much code and I can only test it for DS1307.
Should we wait for [https://github.com/adafruit/RTClib/pull/215](url)? This will make things easier.

2021-05-20 15:24 UTC, ladyada commented
sure!

2021-05-20 15:24 UTC, closed without merging